version: "1.0"

services:
  api:
    image: jnbastos/coredns_api:1.3
    #volumes:
    #  - ./:/home/api
    ports:
      - "8082:8082"
    environment:
      USER: coredns_api
      PATH: "$PATH:/home/api/.local/bin"
    tty: true

  coredns:
    image: coredns/coredns:1.10.0
    container_name: coredns
    hostname: coredns
    restart: always
    ports:
      - "1053:1053/udp"
    volumes:
      - ./coredns/:/etc/coredns
    command: -conf /etc/coredns/Corefile
